### site metadata ###

site_name: Fahmi's Project Library
site_description : Project tech stacks and description detailed by fahmi wahyu wiradika 

copyright: |
  Copyright &copy; 2026 <a href="https://github.com/fahmi-wiradika/fahmi-wiradika.github.io/blob/main/LICENSE"> Fahmi Wahyu Wiradika</a>

### Site Settings ###
#theme : readthedocs --- Optional to use if we don't like to use material theme
theme: 
  name: material
  custom_dir: docs/overrides
  icon:
    annotation: material/arrow-right-circle-outline
    logo: material/bullseye-arrow
    menu: material/bullseye-arrow
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotation
    - content.code.copy
    - navigation.tracking
    - navigation.path
    - navigation.tabs.sticky
    - navigation.footer
    - tabs: true
    ### If page want to be divided to 3 parts then uncomment toc.follow, either using toc.integrate
    # - toc.integrate 
    - toc.follow 
  language: en
  palette:
  # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: indigo
  # Palette toggle for dark mode    
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black
      accent: deep orange
  font: 
    text: Roboto
    code: Roboto Mono

extra_css:
  - stylesheets/home.css
extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js
  # - https://cdn.jsdelivr.net/npm/chart.js@4/dist/chart.umd.min.js
  # - javascripts/mermaid-init.js
  # - javascripts/chart-init.js

extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/fahmi-wiradika
  - icon: simple/postman
    link: https://www.postman.com/fahmi-wiradika
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/fahmi-wiradika
  - icon: fontawesome/brands/instagram
    link: https://www.instagram.com/fahmiwazu
  # alternate:
  #   - name: English
  #     link: /en/ 
  #     lang: en
  #   - name: Indonesia
  #     link: /id/
  #     lang: id

### Navigation Settings ###
### Please to uncomment the document that ready only !!!! ###
nav:
  - Home : index.md
  - Introduction : 
    - About Fahmi: introduction/About-fahmi.md
    - Experience : introduction/Experience-fahmi.md
    - Certification: introduction/Certification-fahmi.md
  - Assignment Project :
    - freeCodeCamp:
      - Relational Database : 
        - Celestial Bodies Database: projects/assignment/relationalDatabase/celestialDB.md
        - World Cup Database: projects/assignment/relationalDatabase/worldCupDB.md
        - Salon Appointment Scheduler: projects/assignment/relationalDatabase/salonDB.md
        - Periodic Table Database: projects/assignment/relationalDatabase/periodicTable.md
        - Number Guessing Game: projects/assignment/relationalDatabase/numberGuessing.md
      - Back End Development and APIs:
#        - Timestamp Microservice: projects/assignment/backendAPI/timeStamp.md
#        - Request Header Parser Microservice: projects/assignment/backendAPI/reqHeaderParser.md
#        - URL Shortener Microservice: projects/assignment/backendAPI/urlShortener.md
        - Exercise Tracer: projects/assignment/backendAPI/exerciseTable.md
#        - File Metadata Microservice: projects/assignment/backendAPI/fileMetadata.md
      - Quality Assurance: 
#        - Metric-Imperial Converter: projects/assignment/qualityAssurance/metricImperialConverter.md
#        - Issue Tracker: projects/assignment/qualityAssurance/issueTracker.md
#        - Personal Library: projects/assignment/qualityAssurance/personalLibrary.md
#        - Sudoku Solver: projects/assignment/qualityAssurance/sudokuSolver.md
        - American-British Translator: projects/assignment/qualityAssurance/american-britishTranslator.md
    - Postman :  
      - API Test Automation: projects/assignment/postman/postmanAutomation.md
#  - Data Structure & Algorithm :
#    - Web Quiz Automation: projects/dataStructureAlgorithm/webQuiz.md
#    - Flexible FizzBuzz Concat: projects/dataStructureAlgorithm/flexibleFizzBuzz.md
#    - Fibonacci Indexes Finder: projects/dataStructureAlgorithm/fibonacciIndex.md
#    - Longest Palindrome : projects/dataStructureAlgorithm/longestPalindrome.md
  - Professional Project:
    - API Testing:
      - JMeter Automation: projects/professional/api-testing/jmeter-automation.md
      - Newman Automation: projects/professional/api-testing/newman-automation.md
    - Web Apps:
      - Simple CRUD Apps: projects/professional/web-apps/simple-crud-apps.md
    - Documentation:
      - Fahmi's Project Library: projects/professional/documentation/docs-portfolio.md
    - Framework:
      - Cypress for Visual Testing: projects/professional/frameworks/cypress.md
      - Java Automation Test: projects/professional/frameworks/java-automation.md
      - Playwright MCP Framework: projects/professional/frameworks/playwright.md
      - Robot Framework Appium: projects/professional/frameworks/appium.md
      - Robot Framework Selenium: projects/professional/frameworks/robot-framework.md
    # - Python Automation Test: projects/workSample/pythonAutomation.md
  - Academic Project:
    - Research :
      - Bachelor Research: projects/academic/research-project/bachelor-research.md
    - Machine Learning:
      - NILM Load Identification: projects/academic/machine-learning/NILM.md
    - Signal Processing:
      - Parseval-Based Power Analysis: projects/academic/signal-processing/frequency-domain-power-analysis.md


# Extensions  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - footnotes
  - tables
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - pymdownx.tabbed:
        alternate_style: true
  - pymdownx.superfences: 
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        # - name: chart
        #   class: chart
        #   format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - autorefs
  # - i18n:
  #     docs_structure: suffix
  #     languages:
  #       - locale: en
  #         name: English
  #         default: true
  #         build: true
  #       - locale: id
  #         name: Bahasa Indonesia
  #         build: true
  - git-revision-date-localized
  - glightbox
